Remove All, error message upon invalid JSON, avoid rewriting several times
pelmers/moz-text-rewriter pull request #9
Opened 2018-10-27 18:55 UTC by JanisE

- Ignore elements whose content was already changed, to avoid rewriting several times
  E.g. replacement "Janis => Janis (author)" could produce "Janis (author) (author) (author) ..."
- Add "Remove All" command
- Display error message upon import failure

2018-11-05 05:46 UTC, pelmers commented
Hi thanks for the PR, I am traveling this week and will take a look when I'm free.

2018-11-05 20:36 UTC, JanisE commented
Maybe should pause with this. It worked for me all right on both Chrome and FF, but today it's acting odd on FF (as a temporary add-on). So maybe more testing/debugging is needed.

2018-11-13 04:21 UTC, pelmers requested changes
just the one comment for clarification, otherwise it looks good and thank you!

2018-11-13 04:21 UTC, pelmers commented on data/text-rewriter.js
> +            if (!cur.textRewriterModified) {
I had previously used the `visitSet` to clear the node visit state between mutation events -- does this approach have the problem where any node is permanently marked modified?

2018-11-14 22:07 UTC, JanisE commented
@pelmers ,

1) I experimented a bit with `WeakSet` (with some 200 elements in the set and >10000 Nodes visited) and realized that it seems to be about as fast as checking for Node property – so I changed the code back to using `WeakSet`, to have less differences from the original code;
2) the main purpose of this pull-request is exactly to mark modified text nodes permanently; in my use case, this is exactly what is needed; not sure how to better approach this if you want it to be universally usable.

My use case is Facebook. For example, if you replace "Peter Elmers" with "Peter Elmers (pelmers)" and open Facebook post or comment by "Peter Elmers", and then hover over his avatar image, a small profile info pop-up will appear including name "Peter Elmers (pelmers)".

If you hover away, the pop-up will disappear. When you now hover again, the same already replaced content is apparently inserted into a new pop-up and/or the pop-up is being re-inserted into the page, so it shows up as a new one in the mutations.

So, this time you'll see "Peter Elmers (pelmers) (pelmers)" for the name. The next time you'll see "Peter Elmers (pelmers) (pelmers) (pelmers)" and so on.

This is what I'm trying to prevent here.

2019-05-07 23:37 UTC, rogersachan commented
@pelmers is this pull request still planned for merge?

2021-10-09 19:29 UTC, pelmers commented
sorry about the 3 year silence @JanisE !
to fix the issue of double-replacement you can now actually encode a negation of the previous value in the regular expression with a lookbehind clause.

For example, let's say I want to replace "car" to "farting car". But I want to make sure I don't get "farting farting car" if the node is updated. Then I can use this rule:

from: (?<!farting )car
to: farting car

2021-10-09 19:29 UTC, closed without merging

2021-10-09 19:40 UTC, JanisE commented
I see, that's a nice feature.

However, if, for example, I want to increase the list depth and want to replace "*" with "**" and I have text like
```
* Lesson A
** Book 1
** Book 2
* Lesson B
** Book 3
```

I'll get
```
** Lesson A
** Book 1
** Book 2
** Lesson B
** Book 3
```

although I wanted to get
```
** Lesson A
*** Book 1
*** Book 2
** Lesson B
*** Book 3
```

2021-10-09 19:51 UTC, pelmers commented
I see, you're right that this is something that regexs can't generalize on their own. Thanks for the example! But for tracking this it seems like we'd have to maintain the set of visited nodes across replacement runs. Even if we did that we wouldn't want to always skip all the nodes we've touched before because that would change the normal behavior of the extension.